---
- hosts: database
  become: yes
  tasks:
    - name: Instalar el software necesario
      apt:
        name: ['mysql-server', 'python3-mysqldb']
        state: present
        update_cache: yes

    - name: Asegurarse de que el servicio MySQL está corriendo
      service:
        name: mysql
        state: started

    - name: Crear la base de datos
      mysql_db:
        name: ansibledb
        state: present

    - name: Crear usuario
      mysql_user:
        name: vagrant
        password: vagrant
        priv: '*.*:ALL,GRANT'
        state: present
...
