# Vagrantfile

Vagrant.configure("2") do |config|

  # Definimos las configuraciones para el servidor web
  config.vm.define "webserver" do |web|
    web.vm.box = "ubuntu/focal64"
    web.vm.hostname = "webserver"
    web.vm.network "private_network", ip: "192.168.56.10"
    web.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1
    end
    web.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook_webserver.yml"
      ansible.inventory_path = "inventory.ini"
    end
  end

  # Configuraciones para la base de datos
  config.vm.define "database" do |db|
    db.vm.box = "ubuntu/focal64"
    db.vm.hostname = "database"
    db.vm.network "private_network", ip: "192.168.56.11"
    db.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    db.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook_database.yml"
      ansible.inventory_path = "inventory.ini"
    end
  end

  # Configuraciones para el servidor de aplicaciones
  config.vm.define "appserver" do |app|
    app.vm.box = "ubuntu/focal64"
    app.vm.hostname = "appserver"
    app.vm.network "private_network", ip: "192.168.56.12"
    app.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end
    app.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook_appserver.yml"
      ansible.inventory_path = "inventory.ini"
    end
  end
end
